name: Go

on:
  release:
    types: [published]

env:
  GOPRIVATE: "github.com"
  CGO_ENABLED: "0"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: git config --global url."https://jasperem:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Build Linux
      env:
        GOOS: "linux"
        GOARCH: "amd64"
      run: go build -o build/otcli_linux cmd/main.go
    
    - name: Build Mac
      env:
        GOOS: "darwin"
        GOARCH: "amd64"
      run: go build -o build/otcli_darwin cmd/main.go

    - name: Build Windows
      env:
        GOOS: "windows"
        GOARCH: "amd64"
      run: go build -o build/otcli_windows.exe cmd/main.go

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/overtime_linux
          build/overtime_darwin
          build/overtime_windows.exe
