
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GOPRIVATE: "github.com"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
  
    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: git config --global url."https://jasperem:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
